### PR TITLE
Fix the formula

### PR DESCRIPTION
**Pull request by asukaminato0721**
I can't find 17,19.

### CODE REVIEW

**Comment by oovm** [comment]
由于 netlify 的某个 bug, 现在的 head 其实在 new 分支上

**Comment by oovm** [comment]
然后另外一些公式渲染 bug, 是 [mathjax#26](https://github.com/vuepress/vuepress-plugin-mathjax/issues/26) 引起的, 这我也没法解决

**Comment by oovm** [comment]
而且你为什么要改文件名啊...

```yaml
5:36:53 PM: [vuepress] No matching page found for sidebar item "/Lv0-炼气/51-60.md"
5:36:53 PM: [vuepress] No matching page found for sidebar item "/Lv0-炼气/51-60.md"
5:36:53 PM: [vuepress] No matching page found for sidebar item "/Lv0-炼气/51-60.md"

5:36:53 PM: TypeError: Cannot read property 'match' of undefined
5:36:53 PM:     at getHash (node_modules/@vuepress/theme-default/util/index.js:13:21)
5:36:53 PM:     at isActive (node_modules/@vuepress/theme-default/util/index.js:47:19)
5:36:53 PM:     at render (node_modules/@vuepress/theme-default/components/SidebarLink.vue:25:0)
5:36:53 PM:     at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:83:0)
5:36:53 PM:     at createFunctionalComponent (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3052:30)
5:36:53 PM:     at createComponent (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3225:12)
5:36:53 PM:     at _createElement (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3415:15)
5:36:53 PM:     at createElement (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3347:10)
5:36:53 PM:     at vm._c (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3484:42)
5:36:53 PM:     at 1.server-bundle.js:801:492
5:36:53 PM:     at Proxy.renderList (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:2624:16)
5:36:53 PM:     at Proxy.SidebarLinksvue_type_template_id_ca47ed18_render (node_modules/@vuepress/theme-default/components/SidebarLinks.vue?756c:1:152)
5:36:53 PM:     at VueComponent.Vue._render (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
5:36:53 PM:     at resolve (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:8415:27)
5:36:53 PM:     at waitForServerPrefetch (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:8287:3)
5:36:53 PM:     at renderComponentInner (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:8426:3)
5:36:54 PM: ​
5:36:54 PM: ┌─────────────────────────────┐
5:36:54 PM: │   "build.command" failed    │
5:36:54 PM: └─────────────────────────────┘
```

**Comment by asukaminato0721** [comment]
> 而且你为什么要改文件名啊...
> 
> ```yaml
> 5:36:53 PM: [vuepress] No matching page found for sidebar item "/Lv0-炼气/51-60.md"
> 5:36:53 PM: [vuepress] No matching page found for sidebar item "/Lv0-炼气/51-60.md"
> 5:36:53 PM: [vuepress] No matching page found for sidebar item "/Lv0-炼气/51-60.md"
> 
> 5:36:53 PM: TypeError: Cannot read property 'match' of undefined
> 5:36:53 PM:     at getHash (node_modules/@vuepress/theme-default/util/index.js:13:21)
> 5:36:53 PM:     at isActive (node_modules/@vuepress/theme-default/util/index.js:47:19)
> 5:36:53 PM:     at render (node_modules/@vuepress/theme-default/components/SidebarLink.vue:25:0)
> 5:36:53 PM:     at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:83:0)
> 5:36:53 PM:     at createFunctionalComponent (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3052:30)
> 5:36:53 PM:     at createComponent (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3225:12)
> 5:36:53 PM:     at _createElement (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3415:15)
> 5:36:53 PM:     at createElement (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3347:10)
> 5:36:53 PM:     at vm._c (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3484:42)
> 5:36:53 PM:     at 1.server-bundle.js:801:492
> 5:36:53 PM:     at Proxy.renderList (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:2624:16)
> 5:36:53 PM:     at Proxy.SidebarLinksvue_type_template_id_ca47ed18_render (node_modules/@vuepress/theme-default/components/SidebarLinks.vue?756c:1:152)
> 5:36:53 PM:     at VueComponent.Vue._render (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
> 5:36:53 PM:     at resolve (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:8415:27)
> 5:36:53 PM:     at waitForServerPrefetch (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:8287:3)
> 5:36:53 PM:     at renderComponentInner (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:8426:3)
> 5:36:54 PM: ​
> 5:36:54 PM: ┌─────────────────────────────┐
> 5:36:54 PM: │   "build.command" failed    │
> 5:36:54 PM: └─────────────────────────────┘
> ```

我是直接在 GitHub 上改的，我也不知道为啥文件名被改了。。

**Comment by asukaminato0721** [comment]
image
试了下，GitHub 在线修改就会变成 rename (没有动文件名) . 那就先不动了。

---

P66

```mma
foo=(x/.FindInstance[x^2-# y^2==1&&x>0&&y>0,{x,y},Integers])[[1]]&;
Last@Ordering[foo/@(Range[1000]/.a_/;IntegerQ[Sqrt[a]]->2)]
```

100 应该是 1000

**Comment by asukaminato0721** [comment]
P19

```mma
Count[DateRange[{1901, 1, 1}, {2000, 12, 31}, Sunday], {_, _, 1, __}]
```

---

P17 写不动，略了。

**Comment by asukaminato0721** [comment]
P76

```mma
PartitionsP[100]-1
```

因为题目是至少 2 个数的和

**Pull request merged**
